import fs from 'node:fs';
import path from 'node:path';
import type { RadarDigest, ScoredRadarRepository } from '../radar/types.js';

export interface ArchiveIndexEntry {
  id: string;
  type: 'daily' | 'weekly';
  date: string;
  title: string;
  path: string;
  summary: string;
  topProjects: string[];
  categoryHighlights: string[];
}

export interface ArchiveIndex {
  updatedAt: string;
  entries: ArchiveIndexEntry[];
}

export interface DigestArchiveWriteResult {
  markdownPath: string;
  jsonPath: string;
  indexPath: string;
  readmePath: string;
  entry: ArchiveIndexEntry;
}

function markdownEscape(value: string): string {
  return value.replace(/\|/g, '\\|').trim();
}

function stat(value: number | null): string {
  return value === null ? 'n/a' : `+${value.toLocaleString()}`;
}

function dateFolder(date: string): { year: string; month: string } {
  const match = date.match(/^(\d{4})-(\d{2})-/);
  if (match) return { year: match[1], month: match[2] };
  const now = new Date();
  return {
    year: date.match(/^(\d{4})/)?.[1] ?? String(now.getUTCFullYear()),
    month: String(now.getUTCMonth() + 1).padStart(2, '0')
  };
}

function archiveId(digest: RadarDigest): string {
  return `${digest.date}-${digest.mode}`;
}

function renderProject(item: ScoredRadarRepository, index: number): string[] {
  const repo = item.repository;
  const summary = item.llmSummary;
  return [
    `### ${index}. ${repo.repoFullName}`,
    `- **Stars:** ${repo.stars.toLocaleString()} (${stat(item.score.dailyStarDelta)} / 24h, ${stat(item.score.weeklyStarDelta)} / 7d)`,
    `- **Category:** ${summary?.aiCategory ?? repo.category}`,
    `- **Why it matters:** ${summary?.whyNow ?? summary?.whyTrending ?? item.whyItMatters}`,
    `- **Developer insight:** ${summary?.developerInsight ?? summary?.developerTakeaway ?? item.developerInsight}`,
    `- **Risk:** ${item.score.riskLevel}`,
    `- [View on GitHub](${repo.repoUrl})`
  ];
}

function renderSourceHealth(digest: RadarDigest): string[] {
  if (!digest.sourceHealth?.length) return [];
  return [
    '## Source Health',
    '',
    '| Source | Items | Status |',
    '|--------|-------|--------|',
    ...digest.sourceHealth.map((source) => `| ${markdownEscape(source.source)} | ${source.itemCount} | ${source.success ? 'OK' : markdownEscape(source.error ?? 'Failed')} |`),
    ''
  ];
}

function renderTrendSignals(digest: RadarDigest): string[] {
  const sections = digest.multiSourceSections;
  if (!sections) return [];
  const lines = ['## Early Signals', ''];
  const items = [
    ...sections.productLaunches,
    ...sections.modelDemoSignals,
    ...sections.developerBuzz,
    ...sections.aihotHighlights
  ].slice(0, 10);

  if (items.length === 0) {
    lines.push('No additional multi-source signals captured.', '');
    return lines;
  }

  items.forEach((item, index) => {
    lines.push(`### ${index + 1}. ${item.title}`);
    lines.push(`- **Source:** ${item.source}`);
    lines.push(`- **Type:** ${item.sourceType}`);
    if (item.category) lines.push(`- **Category:** ${item.category}`);
    if (item.summary ?? item.description) lines.push(`- **Summary:** ${item.summary ?? item.description}`);
    lines.push(`- [Open source item](${item.url})`);
    lines.push('');
  });

  return lines;
}

export function renderArchiveMarkdown(digest: RadarDigest): string {
  const lines = [
    `# AI Developer Radar | ${digest.mode === 'daily' ? 'Daily' : 'Weekly'} | ${digest.date}`,
    '',
    `**Generated:** ${digest.generatedAt}`,
    '',
    '## Today\'s Summary',
    '',
    digest.summary,
    '',
    '## Hot Projects',
    '',
    ...(digest.selectedProjects.length > 0
      ? digest.selectedProjects.flatMap((item, index) => [...renderProject(item, index + 1), ''])
      : ['No selected projects for this run.', '']),
    ...renderTrendSignals(digest),
    ...renderSourceHealth(digest),
    '## Data Notes',
    '',
    ...digest.dataNotes.map((note) => `- ${note}`),
    '',
    '---',
    '',
    '*Generated by [AI Trend Radar](https://github.com/Tsin418/ai-trend-radar)*'
  ];

  return `${lines.join('\n').trim()}\n`;
}

function loadArchiveIndex(indexPath: string): ArchiveIndex {
  if (!fs.existsSync(indexPath)) return { updatedAt: new Date().toISOString(), entries: [] };
  const text = fs.readFileSync(indexPath, 'utf8');
  if (!text.trim()) return { updatedAt: new Date().toISOString(), entries: [] };
  const parsed = JSON.parse(text) as Partial<ArchiveIndex>;
  return {
    updatedAt: parsed.updatedAt ?? new Date().toISOString(),
    entries: parsed.entries ?? []
  };
}

function buildArchiveEntry(digest: RadarDigest, relativeMarkdownPath: string): ArchiveIndexEntry {
  const categoryHighlights = Array.from(new Set(digest.selectedProjects.map((item) => item.llmSummary?.aiCategory ?? item.repository.category))).slice(0, 5);
  return {
    id: archiveId(digest),
    type: digest.mode,
    date: digest.date,
    title: digest.title,
    path: relativeMarkdownPath,
    summary: digest.summary,
    topProjects: digest.selectedProjects.slice(0, 5).map((item) => item.repository.repoFullName),
    categoryHighlights
  };
}

function renderArchiveReadme(index: ArchiveIndex): string {
  const lines = [
    '# AI Trend Radar Archive',
    '',
    `Updated: ${index.updatedAt}`,
    '',
    '| Date | Type | Title | Top Projects |',
    '|------|------|-------|--------------|',
    ...index.entries.map((entry) => `| ${entry.date} | ${entry.type} | [${markdownEscape(entry.title)}](${entry.path}) | ${markdownEscape(entry.topProjects.join(', ') || 'n/a')} |`)
  ];
  return `${lines.join('\n').trim()}\n`;
}

export function writeDigestArchive(digest: RadarDigest, archiveRoot = path.join('data', 'archive')): DigestArchiveWriteResult {
  const { year, month } = dateFolder(digest.date);
  const id = archiveId(digest);
  const relativeMarkdownPath = path.join(year, month, `${id}.md`);
  const relativeJsonPath = path.join(year, month, `${id}.json`);
  const markdownPath = path.join(archiveRoot, relativeMarkdownPath);
  const jsonPath = path.join(archiveRoot, relativeJsonPath);
  const indexPath = path.join(archiveRoot, 'index.json');
  const readmePath = path.join(archiveRoot, 'README.md');
  const entry = buildArchiveEntry(digest, relativeMarkdownPath);
  const index = loadArchiveIndex(indexPath);
  const entries = [entry, ...index.entries.filter((item) => item.id !== entry.id)]
    .sort((a, b) => b.date.localeCompare(a.date));
  const nextIndex: ArchiveIndex = {
    updatedAt: new Date().toISOString(),
    entries
  };

  fs.mkdirSync(path.dirname(markdownPath), { recursive: true });
  fs.writeFileSync(markdownPath, renderArchiveMarkdown(digest), 'utf8');
  fs.writeFileSync(jsonPath, `${JSON.stringify(digest, null, 2)}\n`, 'utf8');
  fs.mkdirSync(path.dirname(indexPath), { recursive: true });
  fs.writeFileSync(indexPath, `${JSON.stringify(nextIndex, null, 2)}\n`, 'utf8');
  fs.writeFileSync(readmePath, renderArchiveReadme(nextIndex), 'utf8');

  return {
    markdownPath,
    jsonPath,
    indexPath,
    readmePath,
    entry
  };
}
